<a href="https://colab.research.google.com/github/woodstone10/fundamental-ml-dl-study/blob/main/gradient_descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# basic machine learning with gradient descent (minimize loss)

In [1]:
import tensorflow as tf
tf.__version__

'2.4.1'

In [2]:
tf.executing_eagerly()

True

### tensor

In [7]:
x = [[1,2]]
y = [[3],[4]]
tf.matmul(x, y)

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[11]], dtype=int32)>

In [9]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.add(a, 1) #broadcasting
b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [11]:
a * b #overloading

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2,  6],
       [12, 20]], dtype=int32)>

In [12]:
import numpy as np
np.multiply(a, b) #tensor used in numpy

array([[ 2,  6],
       [12, 20]], dtype=int32)

## gradient descent

In [13]:
w = tf.Variable([[1.0]])
with tf.GradientTape() as tape:
  loss = w * w

grad = tape.gradient(loss, w)
grad

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[2.]], dtype=float32)>

## basic machine learning with gradient descent (minimize loss)

In [14]:
class Model(tf.keras.Model):
  def __init__(self):
    super(Model, self).__init__()
    self.W = tf.Variable(5., name='weight')
    self.B = tf.Variable(10., name='bias')
  def call(self, inputs):
    return inputs * self.W + self.B

NUM_EXAMPLES = 2000
training_inputs = tf.random.normal([NUM_EXAMPLES])
noise = tf.random.normal([NUM_EXAMPLES])
training_outputs = training_inputs * 3 + 2 + noise

def loss(model, inputs, targets):
  error = model(inputs) - targets
  return tf.reduce_mean(tf.square(error))

def grad(model, inputs, targets):
  with tf.GradientTape() as tape:
    loss_value = loss(model, inputs, targets)
  return tape.gradient(loss_value, [model.W, model.B])

model = Model()
optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)

print("Init Loss: {:.3f}".format(loss(model, training_inputs, training_outputs)))

for i in range(300):
  grads = grad(model, training_inputs, training_outputs)
  optimizer.apply_gradients(zip(grads, [model.W, model.B]))
  if i % 20 == 0:
    print("Step {:03d} Loss: {:.3f}".format(i, loss(model, training_inputs, training_outputs)))

print("Final Loss: {:.3f}".format(loss(model, training_inputs, training_outputs)))
print("W = {}, B = {}".format(model.W.numpy(), model.B.numpy()))

Init Loss: 69.156
Step 000 Loss: 66.437
Step 020 Loss: 29.992
Step 040 Loss: 13.857
Step 060 Loss: 6.712
Step 080 Loss: 3.547
Step 100 Loss: 2.145
Step 120 Loss: 1.523
Step 140 Loss: 1.248
Step 160 Loss: 1.126
Step 180 Loss: 1.071
Step 200 Loss: 1.047
Step 220 Loss: 1.037
Step 240 Loss: 1.032
Step 260 Loss: 1.030
Step 280 Loss: 1.029
Final Loss: 1.028
W = 3.0038578510284424, B = 2.042752742767334
